import os
import re
import subprocess
import tempfile
import numpy as np
import matplotlib.pyplot as plt  
# -----------------------------------------------------------------------------
#  NgSPICE settings
# -----------------------------------------------------------------------------
NGSPICE_CMD   = r"D:\CouchEd_projects\CouchEd\ngspice-42_64\Spice64\bin\ngspice_con.exe"
NGSPICE_FLAGS = ["-b"]      

# -----------------------------------------------------------------------------
#  Netlist builder
# -----------------------------------------------------------------------------
def build_netlist(W_resistances: np.ndarray, x: np.ndarray, rows: int, cols: int, LRS: float, HRS: float,
    R_row_wire: float = 0.1,   
    R_col_wire: float = 0.1    
) -> str:

    lines = []
    lines.append("* Resistor Crossbar MVM - NgSPICE Simulation")
    lines.append(f"* Rows={rows}, Cols={cols}")
    lines.append("")

    lines.append("* -- Input voltage sources ------------------------------")
    for i in range(rows):
        lines.append(f"V_in_{i+1} row_{i+1}_seg_0 0 DC {float(x[i]):.6g}")
    lines.append("")

    lines.append("* -- Row wire segment resistors -------------------------")
    for i in range(rows):
        for k in range(cols - 1):
            node_a = f"row_{i+1}_seg_{k}"
            node_b = f"row_{i+1}_seg_{k+1}"
            lines.append(f"R_row_{i+1}_seg_{k+1}  {node_a}  {node_b}  {R_row_wire:.6g}")
        lines.append("")

    lines.append("* -- Column wire segment resistors ----------------------")
    for j in range(cols):
        for k in range(rows - 1):
            node_a = f"col_{j+1}_seg_{k}"
            node_b = f"col_{j+1}_seg_{k+1}"
            lines.append(f"R_col_{j+1}_seg_{k+1}  {node_a}  {node_b}  {R_col_wire:.6g}")
        lines.append("")

    lines.append("* -- Crossbar Resistors ----------------------------------")
    for i in range(rows):
        lines.append(f"* row{i+1}")
        for j in range(cols):
            if W_resistances[i][j] == 0:
                lines.append(f"R_r{i+1}c{j+1} row_{i+1}_seg_{j}  col_{j+1}_seg_{i} {HRS:.6g}")
            else:
                lines.append(f"R_r{i+1}c{j+1}  row_{i+1}_seg_{j}  col_{j+1}_seg_{i}  {LRS:.6g}")
        lines.append("")

    lines.append("* -- Ammeters (0-V sources for current sensing) ---------")
    for j in range(cols):
        last_col_node = f"col_{j+1}_seg_{rows-1}"
        lines.append(f"V_ammeter_{j+1}  {last_col_node}  0  DC 0")
    lines.append("")

    lines.append("* -- Analysis --------------------------------------------")
    lines.append(".op")
    lines.append("")

    ammeter_list = " ".join(f"I(V_ammeter_{j+1})" for j in range(cols))
    lines.append("* -- Output ----------------------------------------------")
    lines.append(".control")
    lines.append("run")
    lines.append(f"print {ammeter_list}")
    lines.append(".endc")
    lines.append("")
    lines.append(".end")

    return "\n".join(lines)
    
# -----------------------------------------------------------------------------
#  NgSPICE runner
# -----------------------------------------------------------------------------
def run_ngspice(netlist_str: str) -> str:
    # Create a temporary file for the netlist
    with tempfile.NamedTemporaryFile(mode="w", suffix=".sp", delete=False) as f:
        f.write(netlist_str)
        netlist_path = f.name
        
    # Create a matching path for the output log
    log_path = netlist_path + ".log"

    try:
        # Added "-o log_path" to force NgSPICE to write the text to a file
        cmd = [NGSPICE_CMD] + NGSPICE_FLAGS + ["-o", log_path, netlist_path]
        
        # Run the command
        subprocess.run(cmd, capture_output=True, text=True, timeout=60)

        # Read the text directly from the log file generated by NgSPICE
        if os.path.exists(log_path):
            with open(log_path, "r") as f_log:
                return f_log.read()
        else:
            raise RuntimeError("NgSPICE failed to create an output log file.")

    finally:
        # Clean up the temporary files so they don't clutter your hard drive
        if os.path.exists(netlist_path):
            os.unlink(netlist_path)
        if os.path.exists(log_path):
            os.unlink(log_path)

# -----------------------------------------------------------------------------
#  Diagnostic Output parser
# -----------------------------------------------------------------------------
def parse_currents(ngspice_output: str, cols: int) -> np.ndarray:
    currents = np.zeros(cols)
    
    # Check if NgSPICE aborted with an internal error
    if "error" in ngspice_output.lower() or "fatal" in ngspice_output.lower():
        print("\n=== NGSPICE FATAL ERROR DETECTED ===")
        print(ngspice_output)
        print("====================================\n")
        raise RuntimeError("NgSPICE failed to simulate the circuit.")

    for j in range(cols):
        pattern = r"i\(v_ammeter_{}\)\s*[=\s]\s*([+-]?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?)".format(j+1)
        match = re.search(pattern, ngspice_output.lower())
        if match:
            currents[j] = float(match.group(1))
        else:
            # If the regex fails, dump the raw output to the terminal!
            print("\n=== RAW NGSPICE OUTPUT (DEBUG) ===")
            print(ngspice_output)
            print("==================================\n")
            raise ValueError(f"Could not find current for Column {j+1} in output. Please read the RAW OUTPUT above to see why NgSPICE failed.")
            
    return currents

# -----------------------------------------------------------------------------
#  Results Printer
# -----------------------------------------------------------------------------
def print_results(W, x, y):
    rows, cols = W.shape
    sep = "=" * 58

    print("\n" + sep)
    print(f"  Crossbar MVM Result  ({rows} rows x {cols} cols)")
    print(sep)

    print("\nInput voltage vector x:")
    for i, v in enumerate(x):
        print(f"  row_{i+1:<4}  {v:>14.6g}")

    print("\nConductance matrix W (converted from 0/1):")
    for i in range(rows):
        row_str = f"  row_{i+1}:  "
        for j in range(cols):
            row_str += f" {W[i][j]:>10}"
        print(row_str)

    print("\nNgSPICE output currents:")
    print(f"  {'Column':<8}  {'Current (A)':>16}  {'Current (uA)':>14}")
    print("  " + "-" * 42)
    for j, current in enumerate(y):
        print(f"  col_{j+1:<4}  {current:>16.6e}  {current * 1e6:>14.4f}")
    print("\n" + sep + "\n")

def python_cal(W: np.ndarray, x: np.ndarray, rows: int, cols: int, HRS: float, LRS: float) -> np.ndarray:
    # Create an empty array to store the output currents
    output_I = np.zeros(cols)
    for k in range(cols):
        out = 0.0  # Reset 'out' to 0 for each new column   
        for i in range(rows):
            if W[i][k] == 0:
                out = out + (x[i] / HRS)
            else:
                out = out + (x[i] / LRS)
        output_I[k] = out
    print("\n" + "=" * 40)
    print("  Currents calculated using Python (Ideal)")
    print("=" * 40)
    for k in range(cols):
        print(f"  current_in_col_{k+1} = {output_I[k]:.6e} A")
        
    return output_I
    

# -----------------------------------------------------------------------------
#  Main Loop
# -----------------------------------------------------------------------------
if __name__ == "__main__":
    # Added a space here so the prompt looks cleaner in the terminal
    ROWS = int(input("Enter number of ROWS: "))
    COLS = 1          
    HRS = 5.0e+9
    LRS_values = [1.0e3, 5.0e2, 5.0e3]

    # Generate a fixed weight matrix for all tests
    W = np.ones((ROWS, COLS), dtype=int)

    ROW_WIRE_RESISTANCE = 0.1   
    COL_WIRE_RESISTANCE = 0.1   
    
    # --- 1. Set up the empty graph BEFORE the loops start ---
    if COLS == 1:
        plt.figure(figsize=(10, 6))

    for LRS in LRS_values:
        # Reset the amp dictionary for each new LRS value
        amp = {} 
        
        print(f"\n{'='*60}")
        print(f"=== SWEEPING LRS = {LRS:.1e} ===")
        print(f"{'='*60}")

        # Loop from 1 to ROWS (e.g., 1, 2, 3 active inputs)
        for i in range(1, ROWS + 1):
            
            x = np.zeros(ROWS, dtype=int)
            x[:i] = 1
            
            try:
                netlist = build_netlist(W, x, ROWS, COLS, LRS, HRS, R_row_wire=ROW_WIRE_RESISTANCE, R_col_wire=COL_WIRE_RESISTANCE)
                
                raw_output = run_ngspice(netlist)
                currents   = parse_currents(raw_output, COLS)
                print_results(W, x, currents)
                
                amp[i] = currents
                python_cal(W, x, ROWS, COLS, HRS, LRS)
                
                
            except Exception as e:
                print(f"An error occurred: {e}")

        
        if COLS == 1:
            x_values = list(amp.keys())
            y_values_spice = [amp[i][0] * 1e6 for i in x_values]
            plt.plot(x_values, y_values_spice, marker='o', linestyle='-', linewidth=2, markersize=8, label=f'LRS = {LRS:.1e} Ω')

    # --- 3. Format and show the graph AFTER all LRS loops are completely finished ---
    if COLS == 1:
        print("\nGenerating Combined Plot...")
        plt.title(f'Output Current vs. Number of Active Inputs\n({ROWS} Rows × 1 Column | R_wire = {ROW_WIRE_RESISTANCE}Ω)', fontsize=14)
        plt.xlabel('Number of Active Inputs (V = 1V)', fontsize=12)
        plt.ylabel('Output Current (µA)', fontsize=12)
        plt.xticks(x_values)  
        plt.grid(True, linestyle='--', alpha=0.7)
        plt.legend()  # This shows which color belongs to which LRS value
        plt.tight_layout()
        plt.show() # Script halts here, showing all 3 lines at once!
